# ========================= init Section, Node =========================
Section.delete_all
Node.delete_all
s1 = Section.create(name: '信息技术')
Node.create(name: '人工智能', summary: '...', section_id: s1.id)
Node.create(name: '量子计算', summary: '...', section_id: s1.id)
Node.create(name: '区块链', summary: '...', section_id: s1.id)
Node.create(name: '虚拟及增强现实', summary: '...', section_id: s1.id)
Node.create(name: '物联网', summary: '...', section_id: s1.id)
Node.create(name: '信息技术主版', summary: '...', section_id: s1.id)
s2 = Section.create(name: '机械电子')
Node.create(name: '增材制造', summary: '...', section_id: s2.id)
Node.create(name: '机器人', summary: '...', section_id: s2.id)
Node.create(name: '激光制造', summary: '...', section_id: s2.id)
Node.create(name: '微机电系统', summary: '...', section_id: s2.id)
Node.create(name: '半导体与显示器件', summary: '...', section_id: s2.id)
Node.create(name: '机械电子主版', summary: '...', section_id: s2.id)
s3 = Section.create(name: "化学材料")
Node.create(name: '石墨烯/碳材料', summary: '...', section_id: s3.id)
Node.create(name: '复合材料', summary: '...', section_id: s3.id)
Node.create(name: '合金材料', summary: '...', section_id: s3.id)
Node.create(name: '离子液体', summary: '...', section_id: s3.id)
Node.create(name: '催化剂', summary: '...', section_id: s3.id)
Node.create(name: '化学材料主版', summary: '...', section_id: s3.id)
s4 = Section.create(name: '物理能源')
Node.create(name: '电池与储能', summary: '...', section_id: s4.id)
Node.create(name: '核能', summary: '...', section_id: s4.id)
Node.create(name: '太阳能', summary: '...', section_id: s4.id)
Node.create(name: '超导', summary: '...', section_id: s4.id)
Node.create(name: '物理能源主版', summary: '...', section_id: s4.id)
s5 = Section.create(name: '生物医疗')
Node.create(name: '基因测序/精准医疗', summary: '...', section_id: s5.id)
Node.create(name: '靶向药物', summary: '...', section_id: s5.id)
Node.create(name: '干细胞', summary: '...', section_id: s5.id)
Node.create(name: '基因编辑', summary: '...', section_id: s5.id)
Node.create(name: '检测技术', summary: '...', section_id: s5.id)
Node.create(name: '生物医疗主版', summary: '...', section_id: s5.id)
s6 = Section.create(name: '星辰大海')
Node.create(name: '数学', summary: '...', section_id: s6.id)
Node.create(name: '精密测量', summary: '...', section_id: s6.id)
Node.create(name: '地外探索', summary: '...', section_id: s6.id)
Node.create(name: '临近空间/卫星空间', summary: '...', section_id: s6.id)
Node.create(name: '无人机/航空器', summary: '...', section_id: s6.id)
Node.create(name: '海洋极地', summary: '...', section_id: s6.id)
s100 = Section.create(name: '辅助')
Node.create(name: '政策法规', summary: '...', section_id: s100.id)
Node.create(name: '线下活动', summary: '...', section_id: s100.id)
Node.create(name: '招聘', summary: '...', section_id: s100.id)
Node.create(name: '商业需求', summary: '...', section_id: s100.id)
Node.create(name: '发起项目', summary: '...', section_id: s100.id)

s101= Section.create(name: '本站相关')
Node.create(name: '意见问题', summary: '...', section_id: s101.id)
Node.create(name: '公告', summary: '...', section_id: s101.id)
Node.create(name: '违规处理', summary: '...', section_id: s101.id)
#SiteNode.create(name: "国内商业网站", sort: 100)
#SiteNode.create(name: "国外著名网站", sort: 99)
#SiteNode.create(name: "Ruby 社区网站", sort: 98)
#SiteNode.create(name: "技术博客", sort: 97)
#SiteNode.create(name: "Ruby 开源项目", sort: 96)
#SiteNode.create(name: "国内企业", sort: 95)
#SiteNode.create(name: "其他", sort: 94)
